import express from 'express';
import fsPromises from 'fs/promises';
import cors from 'cors';

import { Locations } from './tables/locations.js';
import { Risks  } from './tables/risks.js';

import { 
    createLocation,
    getAllLocations,
    getLocationsByJudet,
    deleteLocation,
    createRisk,
    getAllRisks,
    getRiskById,
    getRisksBySatRel,
    updateRisk,
    deleteRisk
} from './methods.api.js';




const app = express();
app.use(cors());
app.use(express.json());

const PORT = 8080;

//risks 
app.post("/risks", createRisk);
app.get("/risks", getAllRisks);
app.get("/risks/:id", getRiskById);
app.get("/risks/satrel/:satRel", getRisksBySatRel);
app.put("/risks/:id", updateRisk);
app.delete("/risks/:id", deleteRisk);
// CREATE
app.post("/locations", createLocation);
// READ all
app.get("/locations", getAllLocations);
// READ by county
app.get("/locations/judet/:judeti", getLocationsByJudet);
// DELETE
app.delete("/locations/:id", deleteLocation);


/*app.get('/locations/bulkcreate', async (req, res) => {
    await Locations.bulkCreate([
    { judeti: "CLUJ", locatie: "TURDA", numLoc: 47000 },
    { judeti: "CLUJ", locatie: "DEJ", numLoc: 33000 },
    { judeti: "BIHOR", locatie: "ORADEA", numLoc: 196367 }
]);
 res.status(200).send("locations filled")
})CAN BE IGNORED*/

app.get('/risks/bulkcreate', async (req, res) => {
    try {
        await Risks.bulkCreate([
            { 
                info: "High flood risk due to severe weather forecast.", 
                satRel: 9, 
                //arrayStringNumeFisiere: JSON.stringify(["flood_map_q1.pdf", "report_001.txt"])
            },
            { 
                info: "Medium risk of structural failure in sector 3.", 
                satRel: 5, 
                //arrayStringNumeFisiere: JSON.stringify(["sector3_audit.json"])
            },
            { 
                info: "Low risk of equipment malfunction in primary cooling systems.", 
                satRel: 2, 
                //arrayStringNumeFisiere: JSON.stringify(["cooling_log.csv", "maintenance_plan.docx"])
            }
        ]);
        //we should use large text files generated by chatgpt here
        
        // Use a more descriptive status message
        res.status(200).send("Risks table successfully filled with dummy data.");
    } catch (error) {
        console.error("Error during Risks bulkCreate:", error);
        res.status(500).send("Error filling Risks table: " + error.message);
    }
});

// ROUTE: About Page
app.get('/dev1', async (req, res) => {
    try {
        const fileContent = await fsPromises.readFile('./debugPages/datainput.html', 'utf8');
        res.type('html').send(fileContent);
        console.log('Served debugpage.html');
    } catch (error) {
        console.error('Error reading datainput.html:', error.message);
        res.status(500).send('<h1>500 Server Error</h1><p>Failed to load dev1 page file.</p>');
    }
});
app.get('/dev2', async (req, res) => {
    try {
        const fileContent = await fsPromises.readFile('./debugPages/riskinput.html', 'utf8');
        res.type('html').send(fileContent);
        console.log('Served debugpage.html');
    } catch (error) {
        console.error('Error reading datainput.html:', error.message);
        res.status(500).send('<h1>500 Server Error</h1><p>Failed to load dev2 page file.</p>');
    }
});


app.listen(PORT,() => console.log(`test api on http://localhost:${PORT}`))